apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vtrc-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-ssd-lrs-retain
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mapproxy-cache
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard-ssd-lrs-retain
  resources:
    requests:
      storage: 50Gi
