services:
  mapproxy:
    build: ./mapproxy
    image: basemapde/mapproxy
    ports:
      - "8080:8080"
    volumes:
      - ./mapproxy/cache_data:/mapproxy/cache_data
      - ./logs:/logs
      # Web Raster
      #- ./mapproxy/config:/mapproxy/config
      # Pxx
      - ./mapproxy/config_pxx:/mapproxy/config
  converter:
    build: .
    image: basemapde/vt-raster-converter
    #ports:
    #  - "8081:8081"
    environment:
      - LOG_LEVEL=debug # debug, info, warning, error
      - LOG_FILE=/logs/vt-raster-converter.log
      - DATA_PATH=/app/data
      - NODE_MEMORY_LIMIT=8000
    volumes: 
      - ./data:/app/data      
      - ./logs:/logs