name: Rebuild RELEASE images for security updates

on:
  push:
    branches:
      - main  
    paths:
      - ".github/workflows/update-images-release.yml"
  schedule:
    - cron: '0 23 * * 6'


jobs:    
  build-images:
    name: Update docker image ${{ matrix.image }}:${{ matrix.major-tag }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        major-tag: [1.2, 1.2.3, stable]
        image: [${{ secrets.IMAGE_NAME_CONVERTER }}, ${{ secrets.IMAGE_NAME_MAPPROXY }}]
        include: 
          - image: ${{ secrets.IMAGE_NAME_MAPPROXY }}
            context: mapproxy
          - image: ${{ secrets.IMAGE_NAME_CONVERTER }}
            context: .
          - major-tag: 1.2
            minor-tag: 1.2.3            
          - major-tag: 1.2.3
            minor-tag: 1.2.3           
          - major-tag: stable
            minor-tag: 1.2.3                        
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout tag
        run: |
          git checkout tags/${{ matrix.minor-tag }} -b ${{ matrix.minor-tag }}      
      - name: Build an image from Dockerfile
        run: |
          docker build -t ${{ matrix.image }}:${{ matrix.major-tag }} ${{ matrix.context }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ matrix.image }}:${{ matrix.major-tag }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'   
      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.IMAGE_REGISTRY_URL }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
      - name: Push image
        run: |
          docker push ${{ matrix.image }}:${{ matrix.major-tag }}
      - name: Sign image with a key
        run: |
          IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ matrix.image }}:${{ matrix.major-tag }})
          cosign sign --key env://COSIGN_PRIVATE_KEY $IMAGE_SHA
        env:
          COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}                    